# -*- coding: utf-8 -*-
"""MLfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZeQ-qaNzDSRCQuwNPqY3ST7RP8Gs383d
"""

!unzip -q /content/11.zip -d /content/my_11/

# @title
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# 建立一個空的字典，用來收集每個儲存格跑出來的成績
# 因為它建立在全域環境，後面的儲存格都可以把資料塞進來！
final_results_dict = {}

print("基礎設定完成")

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, AveragePooling2D, Flatten, Dense, GlobalAveragePooling2D
from tensorflow.keras.applications import MobileNetV2, InceptionV3
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

IMG_SIZE = (224, 224)
BATCH_SIZE = 64
EPOCHS = 100
#CUSTOM_THRESHOLD = 0.6
train_dir = '/content/my_11/11/train'
test_dir = '/content/my_11/11/test'

print("準備資料生成器")
train_val_datagen = ImageDataGenerator(
    rescale=1./255, rotation_range=10, zoom_range=0.1,
    width_shift_range=0.1, height_shift_range=0.1,
    horizontal_flip=True,
    validation_split=0.2 # Add validation_split here
)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_val_datagen.flow_from_directory(
    train_dir, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='binary', subset='training')
val_generator = train_val_datagen.flow_from_directory(
    train_dir, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='binary', subset='validation')
test_generator = test_datagen.flow_from_directory(
    test_dir, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='binary', shuffle=False)


early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True,
    verbose=1
)

# 讓程式自動抓取 train_generator 裡面的標籤並計算平衡權重
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_generator.classes),
    y=train_generator.classes
)

# 轉換成 Keras 看得懂的字典格式 (例如 {0: 0.56, 1: 4.66})
weights_dict = dict(enumerate(class_weights))
print(f"自動計算的類別權重：{weights_dict}")

def build_lenet():
    model = Sequential([
        Conv2D(6, kernel_size=(5, 5), activation='relu', input_shape=(224, 224, 3)),
        AveragePooling2D(pool_size=(2, 2)),
        Conv2D(16, kernel_size=(5, 5), activation='relu'),
        AveragePooling2D(pool_size=(2, 2)),
        Flatten(),
        Dense(120, activation='relu'),
        Dense(84, activation='relu'),
        Dense(1, activation='sigmoid')
    ], name="LeNet")
    return model


print("正在訓練: LeNet ...")
lenet_model = build_lenet()
lenet_model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])


lenet_model.fit(
    train_generator,
    epochs=EPOCHS,
    validation_data=val_generator,
    class_weight=weights_dict,# 解決資料不平衡
    callbacks=[early_stop],
    verbose=1
)

# 評估與紀錄成績
test_generator.reset()
preds_prob = lenet_model.predict(test_generator, verbose=0)
preds_class = (preds_prob > 0.5).astype(int).flatten() # 這裡可以套用調整過的 Threshold
true_labels = test_generator.classes

final_results_dict['LeNet'] = {
    'Accuracy': accuracy_score(true_labels, preds_class),
    'Recall': recall_score(true_labels, preds_class),
    'Precision': precision_score(true_labels, preds_class),
    'F1-Score': f1_score(true_labels, preds_class)
}

lenet_model.save('lenet_model_final.h5')
print("LeNet訓練完成，模型已存檔")

def build_minivgg():
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(224, 224, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dense(1, activation='sigmoid')
    ], name="MiniVGG")
    return model

print("訓練MiniVGG")
minivgg_model = build_minivgg()
minivgg_model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

# 開始訓練
minivgg_model.fit(
    train_generator,
    epochs=EPOCHS,
    validation_data=val_generator,
    class_weight=weights_dict,
    callbacks=[early_stop],
    verbose=1
)

# 評估與紀錄成績
test_generator.reset()
preds_prob = minivgg_model.predict(test_generator, verbose=0)
preds_class = (preds_prob > 0.5).astype(int).flatten()
true_labels = test_generator.classes

final_results_dict['MiniVGG'] = {
    'Accuracy': accuracy_score(true_labels, preds_class),
    'Recall': recall_score(true_labels, preds_class),
    'Precision': precision_score(true_labels, preds_class),
    'F1-Score': f1_score(true_labels, preds_class)
}

# 存檔
minivgg_model.save('minivgg_model_final.h5')
print("MiniVGG訓練完成，模型已存檔")

def build_transfer_model(base_model_class, model_name):
    base_model = base_model_class(input_shape=(224, 224, 3), include_top=False, weights='imagenet')
    base_model.trainable = False
    x = GlobalAveragePooling2D()(base_model.output)
    x = Dense(128, activation='relu')(x)
    predictions = Dense(1, activation='sigmoid')(x)
    return Model(inputs=base_model.input, outputs=predictions, name=model_name)


print("訓練MobileNetV2")
mobilenet_model = build_transfer_model(MobileNetV2, "MobileNetV2")
mobilenet_model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

mobilenet_model.fit(
    train_generator,
    epochs=EPOCHS,
    validation_data=val_generator,
    class_weight=weights_dict,
    callbacks=[early_stop],
    verbose=1
)

test_generator.reset()
preds_prob = mobilenet_model.predict(test_generator, verbose=0)
preds_class = (preds_prob > 0.5).astype(int).flatten()
true_labels = test_generator.classes

final_results_dict['MobileNetV2'] = {
    'Accuracy': accuracy_score(true_labels, preds_class),
    'Recall': recall_score(true_labels, preds_class),
    'Precision': precision_score(true_labels, preds_class),
    'F1-Score': f1_score(true_labels, preds_class)
}

mobilenet_model.save('mobilenet_model_final.h5')
print("MobileNetV2訓練完成，模型已存檔")

import numpy as np
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

def build_transfer_model(base_model_class, model_name):
    base_model = base_model_class(input_shape=(224, 224, 3), include_top=False, weights='imagenet')
    base_model.trainable = False
    x = GlobalAveragePooling2D()(base_model.output)
    x = Dense(128, activation='relu')(x)
    predictions = Dense(1, activation='sigmoid')(x)
    return Model(inputs=base_model.input, outputs=predictions, name=model_name)

print("正在訓練: MobileNetV2 ...")
mobilenet_model = build_transfer_model(MobileNetV2, "MobileNetV2")
mobilenet_model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

history = mobilenet_model.fit(
    train_generator,
    epochs=EPOCHS,
    validation_data=val_generator,
    class_weight=weights_dict,
    callbacks=[early_stop],
    verbose=1
)

# 使用驗證集尋找最佳 Threshold (目標：最高 Accuracy)
val_generator.reset()
val_preds_prob = mobilenet_model.predict(val_generator, verbose=0)
val_true_labels = val_generator.classes

best_threshold = 0.5
best_acc = 0.0 # 變數名稱改為 best_acc

for thresh in np.arange(0.1, 0.9, 0.05):
    temp_preds_class = (val_preds_prob > thresh).astype(int).flatten()
    current_acc = accuracy_score(val_true_labels, temp_preds_class) # 改用 accuracy_score 計算

    if current_acc > best_acc:
        best_acc = current_acc
        best_threshold = thresh

print(f"找到的最佳Threshold:{best_threshold:.2f} (驗證集 Accuracy: {best_acc:.4f})")

print("\n正在評估測試集成績...")
test_generator.reset()
preds_prob = mobilenet_model.predict(test_generator, verbose=0)

# 把 Threshold 換成剛剛找到的 best_threshold
preds_class = (preds_prob > best_threshold).astype(int).flatten()
true_labels = test_generator.classes

# 將評估結果存成變數
test_acc = accuracy_score(true_labels, preds_class)
test_rec = recall_score(true_labels, preds_class)
test_prec = precision_score(true_labels, preds_class)
test_f1 = f1_score(true_labels, preds_class)

final_results_dict['MobileNetV2'] = {
    'Accuracy': test_acc,
    'Recall': test_rec,
    'Precision': test_prec,
    'F1-Score': test_f1
}

mobilenet_model.save('mobilenet_model_final.h5')

best_epoch_index = np.argmin(history.history['val_loss'])

# 使用該索引值來抓取相對應的 val_accuracy
final_val_accuracy = history.history['val_accuracy'][best_epoch_index]

print("\n" + "="*30)
print("MobileNetV2成績")
print("="*30)
print(f"Validation Accuracy : {final_val_accuracy:.4f}")
print("-" * 30)
print(f"Test Accuracy       : {test_acc:.4f}")
print(f"Test Precision      : {test_prec:.4f}")
print(f"Test Recall         : {test_rec:.4f}")
print(f"Test F1-Score       : {test_f1:.4f}")
print("="*30)

import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator

print("範例圖")

best_model = load_model('mobilenet_model_final.h5')

# 開啟shuffle=True來洗牌
demo_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    shuffle=True
)

labels_map = {v: k for k, v in demo_generator.class_indices.items()}
def get_chinese_label(idx):
    name = labels_map[idx].upper()
    if 'NORM' in name: return 'Normal'
    if 'PNEU' in name: return 'Pneumonia'
    return name

selected_images = []
selected_labels = []

# 不斷抽牌，直到收集滿9張圖 (且確保包含肺炎照片)
while len(selected_images) < 9:
    images, true_labels = next(demo_generator)
    for i in range(len(images)):
        if len(selected_images) < 9:
            selected_images.append(images[i])
            selected_labels.append(true_labels[i])

selected_images = np.array(selected_images)
selected_labels = np.array(selected_labels)


preds_prob = best_model.predict(selected_images, verbose=0)
preds_class = (preds_prob > 0.5).astype(int).flatten()

plt.figure(figsize=(12, 12))

for i in range(9):
    plt.subplot(3, 3, i+1)
    plt.imshow(selected_images[i])

    true_class_name = get_chinese_label(selected_labels[i])
    pred_class_name = get_chinese_label(preds_class[i])

    if preds_class[i] == selected_labels[i]:
        color = 'green'
        icon = '[O]'
    else:
        color = 'red'
        icon = '[X]'

    title = f"{icon} result:{pred_class_name}\n ans:{true_class_name}"

    plt.title(title, color=color, fontsize=14, fontweight='bold', pad=10)
    plt.axis('off')

plt.tight_layout()
plt.show()